### ISSUE TITLE
How to make it work

### ISSUE THREAD

**Issue by aalbul** [develar/ij-rc-producer#1]
Hi,

The idea looks great and to be fair, this is exactly what i was searching for but i cannot make it work on Idea 2016.3

Do i need to do any specific steps after i put it into <PROJECT_ROOT>/.idea/rc-producer.yml?

I tried to invalidate caches, restart project e.t.c. but it still does not work.
When i try to run file, it runs in Mocha not as node.js app.

**Comment by develar** [comment]
IDEA 2017.1+ is required, EAP will be opened soon.
