### ISSUE TITLE
Please provide an option to prevent matching on it() and test()

### ISSUE THREAD

**Issue by nealeu** [develar/ij-rc-producer#3]
Hi,

In trying a Jasmine version, I found that if I don't allow a match for 'it' then some IDEA defaults get provided instead.  It would be good to be able to indicate that the runner (Jasmine in this case) cannot narrow tests down sufficiently.

```
files: ["**/__tests__/**/*", "**/test/**/*", "**/*.(test|spec).*", "**/*Spec.*", "!**/node_modules/**/*"]
script: "./node_modules/jasmine-node/bin/jasmine-node"

lineRegExp: '^\s*(?:test|it|describe)(?:\.[^(]+)?\((?:"|''){1}([^"'']+)'
scriptArgs: ["./test/integration/${fileNameWithoutExt}.js", "--verbose", "--color", "--forceexit", "--junitreport", "--captureExceptions"]
rcName: "${fileNameWithoutExt}.${0}"
```

Jasmine-node's --match doesn't seem to offer the options that would allow us to do as you've shown for the Jest example.

**Comment by develar** [comment]
Hi,

not clear for me — you can write anything in your `rcproducer.yml`.

e.g. you can change 

```
lineRegExp: '^\s*(?:test|it|describe)(?:\.[^(]+)?\((?:"|''){1}([^"'']+)'
```

to

```
lineRegExp: '^\s*(?:describe)(?:\.[^(]+)?\((?:"|''){1}([^"'']+)'
```

to match only `describe`.

Or do you want to disable IDEA default provider?

**Comment by nealeu** [comment]
I'd like to disable the default provider. If I only match describe, I still get the single arrow to run just the test, but that tries running the file with node directly as 

    pathToNode/node <testFilePath>

Also, how do I get the path of the file: is there something like ${filePath} available as an argument? 

I can't currently get a match against files in ./test/unit/ to match and putting in ./test/*/${fileNameWithoutExt}

**Comment by develar** [comment]
> I'd like to disable the default provider

I believe that default provider should be fixed to suit your needs, but not disabled. I asked my colleague to check it.

**Comment by develar** [comment]
> Also, how do I get the path of the file: is there something like ${filePath} available as an argument?

Macro `${file}` will be expanded to a full path.

**Comment by segrey** [comment]
>If I only match describe, I still get the single arrow to run just the test

Thanks for reporting. Looks like a possible solution could be to avoid showing an arrow next to a test if clicking this arrow suggests to run/debug this test file with node, like `node <testFilePath>`.

**Comment by nealeu** [comment]
Ah. I've got update to RC release pending. I'll update. Thanks for the `${file}` macro. That'll help too.

**Comment by segrey** [comment]
@nealeu Sorry for being unclear.
>Looks like a possible solution could be to avoid showing an arrow next to a test if clicking this arrow suggests to run/debug this test file with node, like `node <testFilePath>`.

This suggested solution is not implemented yet. I'll update this issue, once it gets fixed.

**Comment by nealeu** [comment]
No problem.  Always good to keep to bleeding edge so any feedback to you guys isn't wasting time.
